### PR TITLE
Middleware scorepost

### PR DESCRIPTION
**Pull request by Yuqi07**
Java function to handle addScore POST request

### CODE REVIEW

**Comment by erica-w-fu** [comment]
What are these score paths going to be used for?

**Comment by Yuqi07** [comment]
> What are these score paths going to be used for?
It is used to pattern match with the path specified by Julia in DocumentView.js, so that the control flow will direct to this function. Let me know if that makes sense 😄

**Comment by juliawgraham** [comment]
Specifically, it is `Restangular.one('score').post` on line 26 of DocumentView.js

**Comment by erica-w-fu** [comment]
Ohh I see that makes sense. Let's merge

**Comment by Yuqi07** [comment]
Resolved issue #22

**Pull request merged**
