### PR TITLE
Middleware for handling multiple rating PUT requests

### PR DESCRIPTION
**Pull request by Yuqi07**
Resolved issue #6 

- `addSkillScore`: skill scores are integer value between 1 and 5
- `addExperienceScore`: experience scores are integer value between 1 and 5
- `addGPAScore`: GPA scores are floating value between 0 and 4. If the reviewer enters a value not in range, an alert message will be thrown
Screen Shot 2022-10-06 at 15 49 11

### CODE REVIEW

**Comment by juliawgraham** [comment]
Looks good! My only concern is setting $scope.curScore = .... for each of the three scores, as then curScore will just show I believe what the user just inputted and not the actual current score (which should be an average). One possible solution is perhaps calling the average method provided by the backend within each POST request and returning that value, as right now the user inputted score that was given to the PUT request is just being returned.

**Comment by juliawgraham** [comment]
You also mention checking skill/experience score is between 1 and 5. Where are these checks, as I can't seem to find them?

**Comment by Yuqi07** [comment]
> You also mention checking skill/experience score is between 1 and 5. Where are these checks, as I can't seem to find them?

As the score for skill and experience is entered from dropdown, I am assuming it won't anything else from the given option (?) So not explicitly testing that for now. But it's def better to have tests on that as well.

**Comment by Yuqi07** [comment]
> Looks good! My only concern is setting $scope.curScore = .... for each of the three scores, as then curScore will just show I believe what the user just inputted and not the actual current score (which should be an average). One possible solution is perhaps calling the average method provided by the backend within each POST request and returning that value, as right now the user inputted score that was given to the PUT request is just being returned.

That's true. I am wondering do we just to display one score for each axe? For example, if 2 reviewers have rated, do we just display their avg? Or 2 separate scores and an avg? Because for now, I cannot tell from the frontend/UI.

**Comment by juliawgraham** [comment]
> > You also mention checking skill/experience score is between 1 and 5. Where are these checks, as I can't seem to find them?
> 
> As the score for skill and experience is entered from dropdown, I am assuming it won't anything else from the given option (?) So not explicitly testing that for now. But it's def better to have tests on that as well.

Nope, that sounds good. So the tests are implied based on how the frontend works. Thanks for clarifying!

**Comment by Yuqi07** [comment]
Added sanity check so that out-of-range input forced by malicious reviewer will be caught and not enter the database
Screen Shot 2022-10-06 at 20 10 03

For example, if someone directly changes the input value to exceed the range in the UI, it will be detected and an  alert will be thrown.

**Review by juliawgraham — APPROVED** [review]
LGTM!

**Comment by erica-w-fu** [comment]
The warnings all look great! all the namings are as expected :)

**Review by erica-w-fu — APPROVED** [review]
looks good to me!

**Pull request merged**
