### PR TITLE
Frontend for a reviewer to add multiple ratings

### PR DESCRIPTION
**Pull request by erica-w-fu**
Screen Shot 2022-10-05 at 2 19 16 PM
Current score should still be **curscore**. This should now be the average of the three axis and will be displayed as an integer rounded to the second decimal point.

Screen Shot 2022-10-05 at 2 21 19 PM
**score** should still be score. This should now be the average of the three axis rounded down to the nearest integer (to display a whole number amount of yellow/gray stars)

Screen Shot 2022-10-05 at 2 23 05 PM
There should now be these variable and functions:
**skillScore** and **addSkillScore()**
**experienceScore** and **addExperienceScore()**
**academicScore** and **addAcademicScore()**
These represent the three axis of the ratings.

### CODE REVIEW

**Comment by Lucybean-hi** [comment]
Is it possible to change gpa to like an input box? cz <=4.0 gpa makes more sense

**Comment by Yuqi07** [comment]
I'm implementing the middleware now, so just wanna confirm my understanding that we are replacing the addScore function with the 3 specific functions, ie. addSkillScore(), addExperienceScore(), addAcademicScore(). And they should have the same behavior functionality-wise, but for a different score. Please correct me if I am wrong.

**Comment by erica-w-fu** [comment]
> 

@juliawgraham Yep this was what I was thinking

**Comment by erica-w-fu** [comment]
> Is it possible to change gpa to like an input box? cz <=4.0 gpa makes more sense

@Lucybean-hi This is a pretty good idea. When calculating the score though, would we scale the gpa up so that it matches the other dimensions?

**Comment by Lucybean-hi** [comment]
> the

Yes I did that

**Comment by erica-w-fu** [comment]
Changed all the academic score naming to GPA. Also made it so the GPA is entered through a text box!
Screen Shot 2022-10-06 at 11 24 23 AM
We probably need to add validations for the GPA in the middleware now.

Screen Shot 2022-10-06 at 11 25 06 AM
IMPORTANT changed `academicScore` and `addAcademicScore()` to `GPAScore` and `addGPAScore()

**Review by juliawgraham — APPROVED** [review]
All looks good to me!

**Comment by Yuqi07** [comment]
> Changed all the academic score naming to GPA. Also made it so the GPA is entered through a text box! Screen Shot 2022-10-06 at 11 24 23 AM We probably need to add validations for the GPA in the middleware now.
> 
> Screen Shot 2022-10-06 at 11 25 06 AM
> 
> IMPORTANT changed `academicScore` and `addAcademicScore()` to `GPAScore` and `addGPAScore()

I made the corresponding changes to middleware as well.

**Review by Yuqi07 — APPROVED** [review]
image

**Comment by juliawgraham** [comment]
Added the ability for the current score to be updated when changing the scores as well as persist when refreshing the page. This is done through document.__score.

**Pull request merged**
