### PR TITLE
Testing single rating

### PR DESCRIPTION
**Pull request by juliawgraham**
Created a test for PUT /score request. More specifically, it tests that the response contains the correct score and that the resulting document (gotten through GET /document/:id) contains the updated score.

Running the test: 
_cd docs-web 
mvn test -Dtest="TestScoreResource.java"_

### CODE REVIEW

**Comment by Yuqi07** [comment]
if i wanna run your tests, should I checkout your branch first and do a git pull?

**Comment by Yuqi07** [comment]
I tested it locally, and the tests passed!
image

**Comment by Yuqi07** [comment]
lgtm

**Comment by Yuqi07** [comment]
image

**Review by Yuqi07 — APPROVED** [review]
image

**Comment by erica-w-fu** [comment]
Screen Shot 2022-10-06 at 9 28 20 PM
Everything works as expected!

**Review by erica-w-fu — APPROVED** [review]
Looks good to me!

**Comment by juliawgraham** [comment]
Resolves #30

**Pull request merged**
