### PR TITLE
Single rating feature

### LINKED ISSUE #1: UI form for scoring from 1-5
Acceptance Criteria:
Needs to be clear what score is being selected and can properly connect to the middleware

Dependencies:
Need middleware to save scores

### LINKED ISSUE #19: POST request for 5 star rating
Acceptance Criteria:
- the score (1-5) is updated when a reviewer adds a new score
- the score can't be updated when the user is not a reviewer

Dependencies:
- issue https://github.com/CMU-313/fall22-hw3-f4/issues/1 (the frontend needs to have a form that calls the corresponding method in the middleware with the score)

### LINKED ISSUE #21: POST request for 5 star rating - scope
sub issue of #19

### LINKED ISSUE #22: POST request for 5 star rating - post
sub issue of #19

### LINKED ISSUE #27: Add a single score for each document
Update database
Add score attribute to document-related backend files

### PR DESCRIPTION
**Pull request by juliawgraham**
Screen Shot 2022-10-02 at 6 51 47 PM

This feature allows reviewers to add a star rating to each document. This serves as a rating feature for the prospective student's documents, which will prove useful when deciding whether to accept/reject the candidate. If another reviewer wants to change this score, they will override the current score with theirs. Any comments/justification about this score will be simply added within the already implemented comments box. This feature was tested manually by running Teedy (using mvn jetty:run or mvnDebug jetty:run) and by using Chrome developer tools. 

- Resolves #1
- Resolves #19 
- Resolves #21 
- Resolves #22

### CODE REVIEW

**Comment by juliawgraham** [comment]
This feature seems to work well on my end!

**Comment by Yuqi07** [comment]
@juliawgraham Is the parameter score in js of type int or type string? My understanding is that it is string. Pls correct me if I'm wrong. (if it's a string, is this check still valid?)
image

**Comment by juliawgraham** [comment]
@Yuqi07 Huh, currently this is how the function looks like: 

```
/**
    * Add a score.
    */
   $scope.addScore = function () {
     Restangular.one('score').put({
       id: $stateParams.id,
```

Just as you mentioned, the check for scope doesn't make sense as it is a string at that point in the code.

**Comment by Yuqi07** [comment]
> @Yuqi07 Huh, currently this is how the function looks like:
> 
> ```
> /**
>     * Add a score.
>     */
>    $scope.addScore = function () {
>      Restangular.one('score').put({
>        id: $stateParams.id,
> ```
> 
> Just as you mentioned, the check for scope doesn't make sense as it is a string at that point in the code.

My bad, was looking at the old version. LGTM!

**Comment by juliawgraham** [comment]
TODO: fix tests in docs-web so running the build with tests passes

**Comment by juliawgraham** [comment]
Commented out 2 assert statements in TestDocumentResource that were causing tests to fail. This is somehow related to json.getString("rights") but I'm not sure why specifically this is causing tests to fail.

**Review by erica-w-fu — APPROVED** [review]
I just tested by doing mvn clean install and everything looks good!
image

I also ran the code with localhost and everything is working as expected!
Screen Shot 2022-10-03 at 4 37 26 PM

**Comment by Yuqi07** [comment]
I tested locally running `mvn clean install`, and all tests passed successfully.
image

I ran the code with localhost as well, and tested out the single rating feature, which worked as expected.
image

One improvement I noticed is that upon refreshing the page, the score disappears. To optimize, we can later implement a function to handle GET request. For now, at least what we implemented so far is working well.

**Review by Yuqi07 — APPROVED** [review]
LGTM!

**Review by Lucybean-hi — COMMENTED** [review]
Looks good. Fix bugs

**Pull request merged**
